plugins:
  discourse_gamification_enabled:
    default: true
    client: true
  like_received_score_value:   
    default: 1
  like_given_score_value:   
    default: 1
  solution_score_value:   
    default: 10
  user_invited_score_value:   
    default: 10
  time_read_score_value:   
    default: 1
  post_read_score_value:   
    default: 1
  topic_created_score_value:   
    default: 5
  post_created_score_value:   
    default: 2
